imports:
#     - { resource: '@PrestaAssetTinymceBundle/Resources/config/config.yml' }
#     - { resource: 'theme_default.yml' }


doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    PrestaCMSCoreBundle: ~


# Assetic Configuration
assetic:
    bundles:
        - PrestaCMSCoreBundle

sonata_block:
    default_contexts: [cms]
    blocks:
        presta_cms.block.dashboard.cms:
        presta_cms.block.website.selector:
        sonata_admin_doctrine_phpcr.tree_block:
        settings:
            id: '/cms'
            contexts:   [admin]

symfony_cmf_routing_extra:
    chain:
        routers_by_id:
            symfony_cmf_routing_extra.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        controllers_by_class:
            Presta\CMSCoreBundle\Document\Page: presta_cms.page.controller:renderAction
            Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute:  symfony_cmf_routing_extra.redirect_controller:redirectAction
#        templates_by_class:
#            Symfony\Cmf\Bundle\ContentBundle\Document\MultilangStaticContent: PrestaCMSCoreBundle:Page:index.html.twig

#        routing_repositoryroot: /website/prestaconcept/route

knp_menu:
    twig: true

symfony_cmf_menu:
    multilang:
      locales: %locales%

symfony_cmf_tree_browser:
    session_name:  default

fos_js_routing:
    routes_to_expose:
        - symfony_cmf_tree_browser.phpcr_children
        - symfony_cmf_tree_browser.phpcr_move
        - sonata.admin.doctrine_phpcr.phpcrodm_children
        - sonata.admin.doctrine_phpcr.phpcrodm_move
        - presta_cms_page_edit


# CMF
#symfony_cmf_core:
#    document_manager: default
#    role``: IS_AUTHENTICATED_ANONYMOUSLY # used by the publish workflow checker

# app/config/config.yml
#symfony_cmf_content:
#    static_basepath: /content


sonata_doctrine_phpcr_admin:
    confirm_move: true
    document_tree_defaults: [locale]
    document_tree:
        Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode
            image: '/bundles/prestacmscore/admin/img/1x1.png'
        Symfony\Cmf\Bundle\MenuBundle\Document\MultilangMenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Document\MultilangMenuNode
            image: '/bundles/prestacmscore/admin/img/1x1.png'
        Presta\CMSCoreBundle\Document\Page:
            valid_children:
                - Presta\CMSCoreBundle\Document\Page
            image: '/bundles/prestacmscore/admin/img/1x1.png'
        Presta\CMSCoreBundle\Document\Navigation\RootMenuNode:
            valid_children:
                - Presta\CMSCoreBundle\Document\Page
                - Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode
                - Symfony\Cmf\Bundle\MenuBundle\Document\MultilangMenuNode
            image: '/bundles/prestacmscore/admin/img/1x1.png'

sonata_seo:
    encoding: UTF-8
    page:
        title: PrestaCMS by PrestaConcept

twig:
    form:
        resources:
            - 'PrestaCMSCoreBundle:Form:fields.html.twig'
