

# Assetic Configuration
#assetic:
#    bundles:
#        - PrestaCMSCoreBundle

sonata_block:
    default_contexts: [cms]
    blocks:
        presta_cms.block.dashboard.cms:
        presta_cms.block.website.selector:
        sonata_admin_doctrine_phpcr.tree_block:
        settings:
            id: '/cms'
            contexts:   [admin]

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        persistence:
            phpcr:
                enabled: true
        controllers_by_class:
            Presta\CMSCoreBundle\Doctrine\Phpcr\Page: presta_cms.page.controller:renderAction
            Symfony\Cmf\Component\Routing\RedirectRouteInterface:  cmf_routing.redirect_controller:redirectAction
#        templates_by_class:
#            Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\MultilangStaticContent: PrestaCMSCoreBundle:Page:index.html.twig

#        routing_repositoryroot: /website/prestaconcept/route

knp_menu:
    twig: true

cmf_core:
    publish_workflow:
        enabled: false
    multilang:
        locales: %locales%
    persistence:
        phpcr:
            enabled: true

cmf_block:
    persistence:
        phpcr:
            enabled: true

cmf_menu:
    persistence:
        phpcr:
            enabled: true

fos_js_routing:
    routes_to_expose:
        - symfony_cmf_tree_browser.phpcr_children
        - symfony_cmf_tree_browser.phpcr_move
        - sonata.admin.doctrine_phpcr.phpcrodm_children
        - sonata.admin.doctrine_phpcr.phpcrodm_move
        - presta_cms_page_edit


# CMF
#symfony_cmf_core:
#    document_manager: default
#    role``: IS_AUTHENTICATED_ANONYMOUSLY # used by the publish workflow checker

# app/config/config.yml
#symfony_cmf_content:
#    static_basepath: /content


sonata_doctrine_phpcr_admin:
    confirm_move: true
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - Presta\CMSCoreBundle\Doctrine\Phpcr\Menu
                - Presta\CMSCoreBundle\Doctrine\Phpcr\MenuNode
                - Presta\CMSCoreBundle\Doctrine\Phpcr\Page
            image: '/bundles/prestacmscore/admin/img/1x1.png'
        Presta\CMSCoreBundle\Doctrine\Phpcr\MenuNode:
            valid_children:
                - Presta\CMSCoreBundle\Doctrine\Phpcr\MenuNode
            image: '/bundles/prestacmscore/admin/img/1x1.png'
        Presta\CMSCoreBundle\Doctrine\Phpcr\Page:
            valid_children:
                - Presta\CMSCoreBundle\Doctrine\Phpcr\Page
            image: '/bundles/prestacmscore/admin/img/1x1.png'
        Presta\CMSCoreBundle\Doctrine\Phpcr\Menu:
            valid_children:
                - Presta\CMSCoreBundle\Doctrine\Phpcr\MenuNode
            image: '/bundles/prestacmscore/admin/img/1x1.png'

sonata_seo:
    encoding: UTF-8
    page:
        title: PrestaCMS by PrestaConcept

twig:
    exception_controller:  presta_cms.controller.exception:showAction
    form:
        resources:
            - 'PrestaCMSCoreBundle:Form:fields.html.twig'
