security:
    role_hierarchy:
        ROLE_ADMIN_CMS:
            - ROLE_ADMIN_CMS_PAGE
            - ROLE_ADMIN_CMS_WEBSITE
            - ROLE_ADMIN_CMS_THEME
            - ROLE_ADMIN_CMS_SEO
            - ROLE_ADMIN_CMS_CACHE_CLEAR
            - ROLE_ADMIN_CMS_ACCESS

        ROLE_ADMIN_CMS_PAGE:
            - ROLE_ADMIN_CMS_PAGE_ACCESS
            - ROLE_ADMIN_CMS_PAGE_ADD
            - ROLE_ADMIN_CMS_PAGE_EDIT
            - ROLE_ADMIN_CMS_PAGE_DELETE
            - ROLE_ADMIN_CMS_PAGE_MOVE
            - ROLE_ADMIN_CMS_PAGE_STRUCTURE
            - ROLE_ADMIN_CMS_ACCESS

        ROLE_ADMIN_CMS_WEBSITE:
            - ROLE_ADMIN_CMS_WEBSITE_EDIT
            - ROLE_ADMIN_CMS_WEBSITE_ACCESS

        ROLE_ADMIN_CMS_THEME:
            - ROLE_ADMIN_CMS_THEME_EDIT
            - ROLE_ADMIN_CMS_THEME_ACCESS

        ROLE_ADMIN_CMS_SEO:
            - ROLE_ADMIN_CMS_ACCESS
        ROLE_ADMIN_WEBSITE_EDIT:
            - ROLE_ADMIN_CMS_ACCESS
        ROLE_ADMIN_CACHE_CLEAR:
            - ROLE_ADMIN_CMS_ACCESS
        ROLE_ADMIN_THEME_EDIT:
            - ROLE_ADMIN_CMS_ACCESS
        ROLE_ADMIN_CMS_PAGE_ADD:
            - ROLE_ADMIN_CMS_ACCESS
        ROLE_ADMIN_CMS_PAGE_EDIT:
            - ROLE_ADMIN_CMS_ACCESS
        ROLE_ADMIN_CMS_PAGE_DELETE:
            - ROLE_ADMIN_CMS_ACCESS
        ROLE_ADMIN_CMS_PAGE_MOVE:
            - ROLE_ADMIN_CMS_ACCESS
        ROLE_ADMIN_CMS_PAGE_STRUCTURE:
            - ROLE_ADMIN_CMS_ACCESS
