
#Administration - themes
presta_cms_theme:
    pattern:  /cms/theme
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:list}
presta_cms_theme_edit:
    pattern:  /cms/theme/edit/{name}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:edit}
presta_cms_block_edit:
    pattern:  /cms/block/edit/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Block:edit, _sonata_admin: presta_cms.admin.bloc}

presta_cms_block_render:
    pattern:  /cms/block/render/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Block:render, _sonata_admin: presta_cms.admin.bloc}

presta_cms_block_add:
    pattern:  /cms/block/add/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Block:add, _sonata_admin: presta_cms.admin.bloc}
presta_cms_block_delete:
    pattern:  /cms/block/delete
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Block:delete, _sonata_admin: presta_cms.admin.bloc}

#Administration - pages
presta_cms_page_edit:
    pattern:  /cms/page/edit
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:edit}
presta_cms_page_tree:
    pattern:  /cms/page/tree
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:renderPageTree}
presta_cms_page_clear_cache:
    pattern:  /cms/page/clear_cache
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:clearCache}
presta_cms_page_delete:
    pattern:  /cms/page/delete
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:delete}
presta_cms_page_add:
    pattern:  /cms/page/add
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:add}

#Administration - Import / Export
presta_cms_page_selector:
    pattern:  /cms/page-selector/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:selector, website_id: '', locale: ''}

fos_js_routing:
    resource: @FOSJsRoutingBundle/Resources/config/routing/routing.xml

cmf_tree:
    resource: .
    type: 'cmf_tree'
    prefix: /admin/browser
